# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Pipeline de Azure DevOps para Node.js
trigger:
- main
 
pool:
  vmImage: 'ubuntu-latest'
 
stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: Build
    displayName: 'Build job'
    steps:
    trigger:
    - main
 
    pool:
      vmImage: 'ubuntu-latest'
 
    stages:
    - stage: Instalacion
      displayName: 'Instalación'
      jobs:
      - job: Install
        displayName: 'Instalación'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Instalar Node.js'
        - script: |
            npm ci
          displayName: 'npm ci (instalar dependencias)'
 
    - stage: Compilacion
      displayName: 'Compilación'
      dependsOn: Instalacion
      jobs:
      - job: Build
        displayName: 'Compilar'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Instalar Node.js'
        - script: |
            npm run start
          displayName: 'npm run start'
 
    - stage: Pruebas
      displayName: 'Pruebas'
      dependsOn: Compilacion
      jobs:
      - job: UnitTest
        displayName: 'Pruebas unitarias'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Instalar Node.js'
        - script: |
            npm test --silent
          displayName: 'Ejecutar pruebas unitarias'
 
      - job: IntegrationTest
        displayName: 'Pruebas de integración'
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'
          displayName: 'Instalar Node.js'
        - script: |
            echo "Ejecutando pruebas de integración..."
            echo "✓ Configuración validada"
            echo "✓ Dependencias verificadas"
          displayName: 'Integration tests'